### ISSUE TITLE
Does this work for ECS with EC2

### ISSUE THREAD

**Issue by afriportalofficial** [raykrueger/cdk-fargate-public-dns#12]
Please does the tool work with r ECS with EC2? If so do you have a sample?  

Here is my code

```    const serviceTaskDefinition = new ecs.Ec2TaskDefinition(this, `${serviceName}ServiceTaskDef`, {
        networkMode: ecs.NetworkMode.HOST 
    });

    const serviceContainer = serviceTaskDefinition.addContainer( `${serviceName}ServiceContainer`,
      {
        image: ecs.ContainerImage.fromEcrRepository(repository),
        environment: {
        },
        portMappings: [{
            containerPort: 80,
        }],
        logging: ecs.LogDrivers.awsLogs({ streamPrefix: 'my-log-group', logRetention: 30 }),
      }
    );

    // Instantiate an Amazon ECS Service
    const ecsService = new ecs.Ec2Service(this, `${serviceName}Service`, {
      cluster:ecsCluster,
      taskDefinition: serviceTaskDefinition,
    });
    ecsService.connections.allowFromAnyIpv4(ec2.Port.tcp(5000));

    new PublicIPSupport(this, `${serviceName}PublicIPSupport2`, {
        cluster:ecsCluster,
        service:ecsService,
        dnsConfig: {
            domainName: domain.testDomainName,
            hostzedZone: domain.hostedZoneId,
        },
    })```

**Comment by raykrueger** [comment]
Hi! Thanks for the question! My library is built for ECS and Fargate specifically, it really doesn't support EC2. This is because getting the public IP is a very different path. I have thoughts on making one unified library, I just haven't sat down to work on it.

Can you use Fargate here?

**Comment by afriportalofficial** [comment]
Hi Ray, thanks for the response, for my use cases i can't use fargate.
